[package]
name = "dodbot"
version = "2.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serenity]
version = "0.10"

[dependencies.tokio]
version = "1.9"
features = ["rt-multi-thread", "macros", "signal"]

[dependencies.songbird]
version = "0.2.0-beta.4"

[dependencies]
toml = "0.5.8"
parking_lot = "0.11"
rand = "0.8.4"