[package]
name = "dodbot"
version = "2.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serenity]
version = "0.10"

[dependencies.tokio]
version = "1.9"
features = ["rt-multi-thread", "macros"]

[dependencies.songbird]
version = "0.1"

[dependencies]
toml = "0.5.8"