name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_NET_RETRY: 10
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt, rust-src
          override: true

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1

    - name: Rustfmt
      run: cargo +stable fmt --all -- --check

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
